import image1 from "./assets/image1.avif";
import image2 from "./assets/image2.avif";
import image3 from "./assets/image3.avif";
import image4 from "./assets/image4.avif";
import image5 from "./assets/image5.avif";
import image6 from "./assets/image6.avif";
import image7 from "./assets/image7.avif";
import image8 from "./assets/image8.avif";
import image9 from "./assets/image9.avif";
import image10 from "./assets/image10.avif";
import image11 from "./assets/image11.avif";
import image12 from "./assets/image12.avif";
import image13 from "./assets/image13.avif";
import image14 from "./assets/image14.webp";
import image15 from "./assets/image15.avif";
import image16 from "./assets/image16.avif";
import image17 from "./assets/image17.avif";
import image18 from "./assets/image18.avif";
import image19 from "./assets/image19.avif";
import image20 from "./assets/image20.avif";
import image21 from "./assets/image21.avif";
import image22 from "./assets/image22.avif";
import image23 from "./assets/image23.avif";
import image24 from "./assets/image24.avif";
import image25 from "./assets/image25.avif";

export const food_items = [
  {
    id: 1,
    food_name: "Pancakes",
    food_category: "breakfast",
    food_type: "veg",
    food_quantity: 1,
    food_image: image1,
    price: 499,
    description:
      "Fluffy buttermilk pancakes with maple syrup and fresh berries",
    rating: 4.7,
    special_note: "Bestseller breakfast item",
  },
  {
    id: 2,
    food_name: "Chicken Soup",
    food_category: "soups",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image2,
    price: 399,
    description: "Comforting homemade-style chicken broth with vegetables",
    rating: 4.5,
    dietary_info: "Gluten-free option available",
  },
  {
    id: 3,
    food_name: "Minestrone Soup",
    food_category: "soups",
    food_type: "veg",
    food_quantity: 1,
    food_image: image3,
    price: 349,
    description: "Hearty Italian vegetable soup with pasta and beans",
    rating: 4.3,
    seasonal_special: "Winter favorite",
  },
  {
    id: 4,
    food_name: "Spaghetti Carbonara",
    food_category: "pasta",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image4,
    price: 999,
    description: "Classic Roman pasta with pancetta and pecorino cheese",
    rating: 4.8,
    chef_tip: "Best enjoyed immediately",
  },
  {
    id: 5,
    food_name: "Veg Alfredo Pasta",
    food_category: "pasta",
    food_type: "veg",
    food_quantity: 1,
    food_image: image5,
    price: 899,
    description: "Creamy garlic parmesan sauce with seasonal vegetables",
    rating: 4.6,
    spice_level: "Mild",
  },
  {
    id: 6,
    food_name: "Chicken Alfredo Pasta",
    food_category: "pasta",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image6,
    price: 1099,
    description: "Rich creamy pasta with grilled chicken strips",
    rating: 4.7,
    best_pairing: "Garlic bread",
  },
  {
    id: 7,
    food_name: "Paneer Butter Masala",
    food_category: "main_dishes",
    food_type: "veg",
    food_quantity: 1,
    food_image: image7,
    price: 799,
    description: "North Indian cottage cheese in tomato cream gravy",
    rating: 4.9,
    spice_level: "Medium",
  },
  {
    id: 8,
    food_name: "Chicken Biryani",
    food_category: "main_dishes",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image8,
    price: 1199,
    description: "Fragrant basmati rice with spiced chicken layers",
    rating: 4.8,
    cooking_time: "45 mins",
  },
  {
    id: 9,
    food_name: "Margherita Pizza",
    food_category: "pizza",
    food_type: "veg",
    food_quantity: 1,
    food_image: image9,
    price: 649,
    description: "Neapolitan-style pizza with fresh basil and mozzarella",
    rating: 4.6,
    crust_type: "Wood-fired",
  },
  {
    id: 10,
    food_name: "Pepperoni Pizza",
    food_category: "pizza",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image10,
    price: 749,
    description: "Classic American pizza with spicy pepperoni slices",
    rating: 4.7,
    bestseller: true,
  },
  {
    id: 11,
    food_name: "Veggie Burger",
    food_category: "burger",
    food_type: "veg",
    food_quantity: 1,
    food_image: image11,
    price: 499,
    description: "Plant-based patty with fresh vegetables and sauces",
    rating: 4.4,
    vegan_option: true,
  },
  {
    id: 12,
    food_name: "Chicken Burger",
    food_category: "burger",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image12,
    price: 599,
    description: "Juicy grilled chicken breast with special sauce",
    rating: 4.6,
    combo_offer: "With fries + drink",
  },
  {
    id: 13,
    food_name: "Tomato Soup",
    food_category: "soups",
    food_type: "veg",
    food_quantity: 1,
    food_image: image13,
    price: 299,
    description: "Creamy roasted tomato soup with herb croutons",
    rating: 4.2,
    comfort_food: true,
  },
  {
    id: 14,
    food_name: "Egg Sandwich",
    food_category: "breakfast",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image14,
    price: 349,
    description: "Scrambled eggs with cheddar cheese on toasted bread",
    rating: 4.3,
    quick_serve: true,
  },
  {
    id: 15,
    food_name: "Mushroom Soup",
    food_category: "soups",
    food_type: "veg",
    food_quantity: 1,
    food_image: image15,
    price: 349,
    description: "Creamy wild mushroom soup with truffle oil",
    rating: 4.4,
    premium_ingredient: "Porcini mushrooms",
  },
  {
    id: 16,
    food_name: "Chicken Tikka Masala",
    food_category: "main_dishes",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image16,
    price: 1199,
    description: "Tandoori chicken in rich tomato cream sauce",
    rating: 4.8,
    origin: "British-Indian fusion",
  },
  {
    id: 17,
    food_name: "Cheese Omelette",
    food_category: "breakfast",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image17,
    price: 399,
    description: "Three-egg omelette with cheddar and herbs",
    rating: 4.1,
    customizable: "Add veggies or meats",
  },
  {
    id: 18,
    food_name: "Fettuccine Alfredo",
    food_category: "pasta",
    food_type: "veg",
    food_quantity: 1,
    food_image: image18,
    price: 949,
    description: "Classic Italian pasta in parmesan cream sauce",
    rating: 4.5,
    pasta_type: "Fresh handmade",
  },
  {
    id: 19,
    food_name: "Garlic Bread",
    food_category: "pizza",
    food_type: "veg",
    food_quantity: 1,
    food_image: image19,
    price: 299,
    description: "Crusty bread with garlic butter and herbs",
    rating: 4.0,
    perfect_with: "Any soup or pasta",
  },
  {
    id: 20,
    food_name: "Fish and Chips",
    food_category: "main_dishes",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image20,
    price: 1099,
    description: "Beer-battered cod with crispy fries",
    rating: 4.6,
    traditional: "British classic",
  },
  {
    id: 21,
    food_name: "Hash Browns",
    food_category: "breakfast",
    food_type: "veg",
    food_quantity: 1,
    food_image: image21,
    price: 249,
    description: "Crispy golden potato patties",
    rating: 4.2,
    best_served: "Hot and crispy",
  },
  {
    id: 22,
    food_name: "Vegetable Soup",
    food_category: "soups",
    food_type: "veg",
    food_quantity: 1,
    food_image: image22,
    price: 329,
    description: "Chunky garden vegetables in light broth",
    rating: 4.3,
    low_calorie: true,
  },
  {
    id: 23,
    food_name: "Egg Fried Rice",
    food_category: "main_dishes",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image23,
    price: 599,
    description: "Wok-tossed rice with vegetables and scrambled egg",
    rating: 4.4,
    wok_hei: "Authentic smoky flavor",
  },
  {
    id: 24,
    food_name: "Hawaiian Pizza",
    food_category: "pizza",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image24,
    price: 799,
    description: "Ham and pineapple on tomato sauce base",
    rating: 4.1,
    controversial: "Love it or hate it!",
  },
  {
    id: 25,
    food_name: "Pasta Primavera",
    food_category: "pasta",
    food_type: "veg",
    food_quantity: 1,
    food_image: image25,
    price: 899,
    description: "Spring vegetables in light olive oil sauce",
    rating: 4.5,
    seasonal: "Spring special",
  },
];
